// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#pragma once

#define MIRYOKU_LAYERS_FLIP
#define MIRYOKU_NAV_INVERTEDT

#define MIRYOKU_LAYER_BASE   MIRYOKU_ALTERNATIVES_BASE_COLEMAKDH_FLIP
#define MIRYOKU_LAYER_EXTRA  MIRYOKU_ALTERNATIVES_BASE_QWERTY_FLIP
#define MIRYOKU_LAYER_TAP    MIRYOKU_ALTERNATIVES_TAP_COLEMAKDH_FLIP
#define MIRYOKU_LAYER_BUTTON MIRYOKU_ALTERNATIVES_BUTTON
#define MIRYOKU_LAYER_NAV    MIRYOKU_ALTERNATIVES_NAV_INVERTEDT_FLIP
#define MIRYOKU_LAYER_MOUSE  MIRYOKU_ALTERNATIVES_MOUSE_INVERTEDT_FLIP
#define MIRYOKU_LAYER_MEDIA  MIRYOKU_ALTERNATIVES_MEDIA_INVERTEDT_FLIP
#define MIRYOKU_LAYER_NUM    MIRYOKU_ALTERNATIVES_NUM_FLIP
#define MIRYOKU_LAYER_SYM    MIRYOKU_ALTERNATIVES_SYM_FLIP
#define MIRYOKU_LAYER_FUN    MIRYOKU_ALTERNATIVES_FUN_FLIP